apiVersion: apps/v1
kind: Deployment
metadata:
  name: mecanica-api
  namespace: ${namespace}
  labels:
    tags.datadoghq.com/env: "prd"
    tags.datadoghq.com/service: "mecanica-api"
    tags.datadoghq.com/version: "1.0.0" 
spec:
  selector:
    matchLabels:
      app: mecanica-api
  template:
    metadata:
      labels:
        app: mecanica-api
        tags.datadoghq.com/env: "prd"
        tags.datadoghq.com/service: "mecanica-api"
        tags.datadoghq.com/version: "1.0.0" 
      annotations:
        # Instrução para o Operator injetar o agente Java automaticamente
        instrumentation.opentelemetry.io/inject-java: "java-instrumentation"
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: mecanica-api
          image: ${api_image}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: mecanica-api-secret
            - configMapRef:
                name: mecanica-api-config
          env:
          - name: DD_ENV
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/env']
          - name: DD_SERVICE
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/service']
          - name: DD_VERSION
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/version']
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            failureThreshold: 6
            periodSeconds: 5
            timeoutSeconds: 3
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            failureThreshold: 30
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true # Bloqueia o disco contra gravações indevidas
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp # Necessário para o Spring Boot rodar com readOnlyRootFilesystem
      volumes:
        - name: tmp-volume
          emptyDir: {}
